# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "qr-code-generator"
client_id = "e15ac2ff184407a0075831dad896075d"
application_url = "https://films-paypal-matt-ceiling.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://films-paypal-matt-ceiling.trycloudflare.com/auth/callback",
  "https://films-paypal-matt-ceiling.trycloudflare.com/auth/shopify/callback",
  "https://films-paypal-matt-ceiling.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mot-app-playground.myshopify.com"
